### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by skydiver1980**

### CODE REVIEW

**Review by skydiver1980 — COMMENTED** [review]
Is this done?

**Comment by Endor8** [comment]
Hi.
This account probably will be set to private soon.
I am only collector of scripts. The major part her is a fork of
Ardiman and he is not active any more. So more the 95% of the
stuff here never works and is dead.  I not have time for keeping this 
alive nor have i the abilities.  Sorry.

**Review by skydiver1980 — COMMENTED** [review]
Ty

**Review by skydiver1980 — COMMENTED** [review]
Redo

**Pull request closed without merging**
